# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5ca8da7fae476ab67be8708fba96aeaa"
name = "bf-test-app"
handle = "bf-test-app"
application_url = "https://shopify-app-ten-pi.vercel.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_products,read_fulfillments,write_app_proxy,write_discounts,unauthenticated_read_content"

[auth]
redirect_urls = [
  "https://shopify-app-ten-pi.vercel.app/auth/callback",
  "https://shopify-app-ten-pi.vercel.app/auth/shopify/callback",
  "https://shopify-app-ten-pi.vercel.app/api/auth/callback"
]

[pos]
embedded = false

[[web]]
role = "backend"
command = 'cmd /c "cd ..\shopify-flow-billing-server && npm run start:dev"'
port = 3_000
paths = [
  "/webhooks/*",
  "/api/auth/*",
  "/flow-action/handle",
  "/graphql"
]
